### PR TITLE
Turkish Translation Update

### PR DESCRIPTION
**Pull request by hazarek**
# The following missing translation files have been translated and added;
- PrefUtilsViewController
- OpenURLWindowController
- MiniPlayerWindowController
- PreferenceWindowController

# Unnecessary brackets removed. 
"alert.config.cannot_create" = "Yapılandırma **(config file)** dosyası oluşturulamıyor!\n%@";

### CODE REVIEW

**Comment by hazarek** [comment]
No Turkish option, will it be in the next update? 
cap

**Comment by alejx** [comment]
@hazarek Yes, of course.

**Comment by alejx** [comment]
Merged locally. I'll try to include tr localization into 1.0.5.

**Comment by hazarek** [comment]
> Merged locally. I'll try to include tr localization into 1.0.5.

thanks good works

**Pull request merged**
