### PR TITLE
Changes to grammar and syntax of General prefs

### PR DESCRIPTION
**Pull request by hughlilly**
Some minor changes to the grammar and syntax of various phrases in the General part of the main preferences window.

### CODE REVIEW

**Comment by hughlilly** [comment]
This is my first pull request on a project that is not one of my own repos. I hope I have not done anything wrong. Please let me know if I have.

**Comment by lhc70000** [comment]
Looks good to me. Thanks for your contribution!

**Comment by hughlilly** [comment]
Thank you. Is it safe to delete my fork? I'm not sure how this works. Will the messages on this pull request stay intact or will they be deleted? Thanks. 
image

**Comment by saagarjha** [comment]
Yes, you can delete your fork. All of your contributions to IINA will remain intact here, along with the discussion. Any code you didn't include in the pull request will be deleted, however.

**Pull request merged**
