### PR TITLE
Update icons to adhere to latest HIG, #4279

### LINKED ISSUE #4279: Document icons do not adhere to the latest HIG
**System and IINA version:**

- macOS 13.2.1
- IINA 1.3.1

**Expected behavior:**
IINA adheres to Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/guidelines/overview/).

**Actual behavior:**
In macOS Big Sur Apple introduced many user interface changes. The changes included altering the stylistic requirements for [app and document icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/document-icons/) specified in the Human Interface Guidelines. IINA's icons have not been updated to adhere to the new HIG requirements.

**Steps to reproduce:**
See IINA discussion #3670 for an excellent explanation from @Zabriskije of the ways in which IINA's current icons deviate from the updated HIG requirements.

### PR DESCRIPTION
**Pull request by low-batt**
In macOS Big Sur Apple introduced many user interface changes. The changes included changing the requirements for app and document icons specified in the Human Interface Guidelines. The commit updates IINA's app icon and all of the document icons to adhere to the current HIG. The changes are subtle. See IINA discussion #3670.

Thank you @Zabriskije for creating the updated icons.

This commit will:
- Update the app icon
- Update all of the document icons

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4279.

---

**Description:**
See the comments in discussion #3670.

### CODE REVIEW

**Comment by saagarjha** [comment]
We should probably be using the system API to generate document icons, no?

**Comment by low-batt** [comment]
I believe the answer is no, IINA must still supply document icons, based on this guidance from the HIG _at the time this work was done_:

>If you don’t supply a document icon for a file type you support, macOS 11 creates one for you by compositing your app icon and the file’s extension onto the canvas.
>
>If your app runs in earlier versions of macOS, you should supply a legacy document icon. If you let earlier versions of macOS generate a document icon for you, you get different results in different versions. Specifically, macOS 10.15 creates a document icon by compositing your app icon, but not the file extension; macOS 10.14 and earlier use a generic document background if you don’t supply any assets.

A year ago when Zabriskije did this work the HIG still contained that text. With the release of macOS 13, Apple has been removing documentation about releases earlier than macOS 11. I can no longer find that text in the HIG. I copied it from my first reply to the icon discussion [here](https://github.com/iina/iina/discussions/3670#discussioncomment-2411793).

I think IINA can't rely upon macOS generated document icons until macOS 11 is the oldest version supported.

**Comment by Zabriskije** [comment]
@low-batt, you legend. Thanks for remembering and taking the time to create the pull request.
May I be included as a co-author?

About the @saagarjha question: low-batt is right. Publishing with support for older macOS versions would create legacy document icons instead of the new one with a "flat" style (If I recall correctly). Results may vary depending on the aftermentioned and the Xcode/macOS version used.

**Comment by low-batt** [comment]
@Zabriskije Great to hear from you. As far as I am concerned you are the primary contributor. I was unaware of GitHub's ability to specify a co-author when creating a commit as documented [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). I think I have successfully amended the commit to include you.

Back when I created the commit the team had to focus on critical defects, so I did not post a PR. Plans are not set, but it is looking like the next release will also be a bug fix release and then we will work on a feature release. I created this PR/issue so I could add this to the list of changes to consider for the feature release.

**Pull request merged**
