### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by revolter**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

### CODE REVIEW

**Comment by lhc70000** [comment]
Sorry for the delay and thanks for the correction. However, you should change `Base.lproj` and `en.lproj` only. Do you want to submit another patch or let me fix this?

**Comment by lhc70000** [comment]
I just found that #2914 fixed this problem so I'm closing this one. Sorry!

**Comment by revolter** [comment]
No problem, but, could you please tell me why shouldn't I have changed the other files too?

**Comment by alejx** [comment]
Cuz our whole localization process is managed by Crowdin, so if you change the strings file of the languages other than English, there'll be conflicts when we merge new translations from Cowdin.

**Pull request closed without merging**
