### PR TITLE
Handle power key correctly

### PR DESCRIPTION
**Pull request by HarukaMa**
Prevent crash on certain key combinations such as control+shift+power.

### CODE REVIEW

**Comment by HarukaMa** [comment]
Should "fix" #155

**Comment by lhc70000** [comment]
Are you sure this key code is consistent on all devices we support?

**Comment by HarukaMa** [comment]
@lhc70000 ...I'm not even sure the power button should be 127, but currently the log says so...

**Comment by HarukaMa** [comment]
fd10402b-2379-405b-a589-2c0c6d1d03a2

0x7F should be okay I think.

**Pull request merged**
