### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by shilch**
Hi,
thank you for this nice media-player!

Since IINA was available in English and Simplified Chinese only, I added German translations as far as possible - some Strings seemed to be not configurable using the translation files. Since German is my mother tongue the translations are not always word-by-word but they retain their meaning.

As Germany text is most time longer than text in other languages it gets cut off:
Screenshot
It seems to be easy to fix in the .xib files but since I am not a macOS developer and used Xcode the first time I broke the layout all time and revert the changes. But I think you can do it.

shilch

PS: Accidentally commited to master but it doesn't seem to matter in this case.

### CODE REVIEW

**Comment by Miigon** [comment]
Nice Job!
@lhc70000 I wonder if we can add translation for `General` `UI` `Codec`Tabs

**Comment by lhc70000** [comment]
Thank you for your effort.

Currently I think IINA is not ready for a serious localization. I'll fix the width problem and add string files for preference tabs as soon as possible.

Once it's ready, I'll update here.

**Comment by Miigon** [comment]
Yeah,I also found that some of the strings are hard coded in the source file.

**Comment by rschiang** [comment]
Ready for Trad Chinese localization here! (@l10n-tw
Please let us know when it's ready. :)

**Comment by lhc70000** [comment]
@rschiang Thanks a lot!

**Comment by alephmelo** [comment]
I can help with Portuguese :brazil: when it's ready.

**Comment by shilch** [comment]
Nice! I think currently IINA is mainly downloaded by GitHub users. Translating IINA increases user experience a lot which probably results into more downloads by end-users.

**Comment by lhc70000** [comment]
Hi everyone, I think IINA is ready for localization now.

For existing PR (@shilch), please take a look at `Localizable.strings` as well as xib files since they may be updated.

For other languages (@alephmelo, @rschiang), please open new PRs for translation.

- Please read `CONTRIBUTING.md` for some common guidelines.
- Please check whether AutoLayout works, i.e. preference panel will adjust width automatically for longer content.
- If there's any question, please feel free to ask me on github, via email or in Telegram group.
- Please stay connected since IINA is in rapid development so there may be new features waiting for translation soon.

**Comment by shilch** [comment]
@lhc70000 Done
screenshot

**Pull request merged**
