### PR TITLE
Move to macos-latest and xcode 15.4 on CI

### PR DESCRIPTION
**Pull request by Goooler**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [ ] This implements/fixes issue #.

---

**Description:**

Now macos-latest is based on macos-14 with arm64.

See 
- https://github.com/actions/runner-images?tab=readme-ov-file#available-images
- https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode

### CODE REVIEW

**Comment by uiryuu** [comment]
What's the latest Xcode available, should we also update Xcode as well?

**Comment by Goooler** [comment]
It's 15.2 on runner image, see https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode.

**Comment by Goooler** [comment]
You can always check the bundled versions at https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#xcode.

**Comment by uiryuu** [comment]
Thanks!

**Pull request merged**
