### PR TITLE
Clean up string files for the base language (en)

### PR DESCRIPTION
**Pull request by alejx**
We are going to use [crowdin.com](https://crowdin.com) to do the localization in the future. Everyone who is interested in helping localize or improve the current localiztion can visit [translate.iina.io](https://translate.iina.io) and register an account for free.

Crowdin has an elegent way to show the completeness of each language, compare to the base language. This PR removes the strings that are not needed to be translated, so that Crowdin can give us a better completeness of each language.

Please help me to find any string that shouldn't be removed in this PR, thanks!

### CODE REVIEW

**Comment by alejx** [comment]
- fr @superzazu
- it @cgand
- de @J-rg @shorshe 
- ko @darkbrow
- ru @euf @imKota @Semty
- ja @matsune, @LEoREo2247 
- nl @ErikMinekus
- es @Aikyuichi
- uk @AthirnEleidan
- sk @marianvinicay
- pt-BR @pradorocchi, @ailtonvivaz 
- sv @anohren 
- ro @sfDuhNinja
- hi @SensehacK
- cs @vojtakonarik 
- zh-Hans -
- zh-Hant -
- da @thkir 
- tr @eminhaqi, @hazarek 
- pl @Greenek

Please do not send any PR regarding localization directly to this repo. If you are still interested in improving localiztions in your language for IINA, please consider registering an account and contribute at [translate.iina.io](https://translate.iina.io). Thanks!

**Comment by alejx** [comment]
Btw please do not contribute on [translate.iina.io](https://translate.iina.io) until this PR is merged, thanks.

**Comment by hazarek** [comment]
@alejx Why are these files that I've translated do not exist on the [translate.iina.io](https://translate.iina.io)?  https://github.com/iina/iina/pull/2680#issue-359202853

**Comment by hazarek** [comment]
whatever, it does not matter. I will translate again by new site.

**Comment by lhc70000** [comment]
@hazarek It's because the 1.0.5 branch is not merged to develop. You don't need to translate them in the new site and they will be available there in a few days.

**Pull request merged**
