### PR TITLE
Change the text color in inspector from `textColor` to `labelColor`

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)

---

**Description:**
This commit increases the sharpness of the text fields. This is especially obvious when the background is a light color.

Before:
image

After:
image

### CODE REVIEW

**Comment by low-batt** [comment]
It also changes the look of the capitalized titles as can be seen when comparing `VIDEO` in the screenshots above.

I've always wondered about the choice to make this window very transparent. It can be hard to read depending upon the background.

**Comment by uiryuu** [comment]
> It also changes the look of the capitalized titles as can be seen when comparing VIDEO in the screenshots above.

I didn't touch the VIDEO and AUDIO labels, nor it can be seen in diff. But I guess it's not bad to make them bold.

**Comment by uiryuu** [comment]
> It also changes the look of the capitalized titles as can be seen when comparing VIDEO in the screenshots above.

The "before" image was taken on the 1.3.5 release version, so the capitalized titles should be changed by one of @svobs' PRs.

**Comment by low-batt** [comment]
Ah. My mistake. I too was comparing against 1.3.5. I should have checked it against `develop`.

**Comment by low-batt** [comment]
This was included in IINA 1.4.0.

**Pull request merged**
