### PR TITLE
Close support subtitle visibility, #4235

### LINKED ISSUE #4235: Support subtitle visibility
**What you want IINA to do:**
This is a request for IINA to directly support the mpv options [sub-visibility](https://mpv.io/manual/stable/#options-no-sub-visibility) and [secondary-sub-visibility](https://mpv.io/manual/stable/#options-no-secondary-sub-visibility). These options disable/enable the rendering of subtitles, similar to muting audio.

Support must include menu items to toggle the state. The menu items must adhere to Apple's Human Interface Guidelines on [Menus](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/menus), specifically the section on `Toggled items`.

IINA already has a `Subtitles` menu so new menu items must be under that menu. The current convention in the menu is to use the prefix `Second` for items that pertain to secondary subtitles. I suggest using `Visible` and `Second Visible` for the names of the items with checkmarks to indicate the state.

The menu items must include associated keyboard shortcuts. The key bindings used by mpv are:

| Key | Command |
| --- | --- |
| v | cycle sub-visibility |
| Alt+v | cycle secondary-sub-visibility |

IINA does not currently contain bindings for these keys so IINA should use the same bindings as mpv.

When subtitle visibility changes an OSD message must be shown so the user knows if subtitle rendering is enabled or disabled.

This request originates out of discussions concerning issue #4234.

**What IINA does currently:**
Currently this mpv feature is only available through custom key bindings, which does not provide feedback to the user as to the current state of subtitle visibility.

**Why you think this should be added:**
Subtitles is one area where IINA has a feature not found in mpv (without plugins), the ability to download from web sites that provide subtitles. IINA should insure other subtitle functions are supported. The mpv subtitle visibility feature is a convenience feature similar to being able to quickly mute audio.

**Examples of other projects that have something similar:**
This is a mpv feature.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Add a Hide Subtitles/Show Subtitles item to the Subtitles menu
- Add a Hide Second Subtitles/Show Second Subtitles item to the Subtitles menu
- Add a key binding mapping v to cycle sub-visibility
- Add a key binding mapping Alt-v to cycle secondary-sub-visibility
- Add a new OSD message Subtitle Visibility: On/Off
- Add a new OSD message Second Subtitle Visibility: On/Off
- Add secondary-sub-visibility to watch-later-options
- Add logging of watch-later-options

These changes add a graphical user interface for the mpv features that control subtitle visibility.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4235.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
See the issue for a screen shot of what the `Subtitles` menu looks like with the new items.

**Missing** is integration with the plugin API. Should this be exposed to plugins?

**Comment by svobs** [comment]
Instead of "Subtitle Visibility: On/Off", how about "Subtitles Visible" / "Subtitles Hidden"?

**Comment by low-batt** [comment]
I think I was too focused on making the new OSD messages follow the patterns in the existing messages. I've updated the PR to use the suggested messages. I added screen shots of the new messages to the issue.

The other thing that is **missing** from the PR is support for the visibility feature in the `SUBTITLES` tab of the quick setting panel. Need to look into that.

**Comment by low-batt** [comment]
I converted this to a draft as I am working on adding support to the `SUBTITLES` tab of the quick setting panel.

**Comment by low-batt** [comment]
The latest changes rebase with `develop` and add two switches to the `Quick Setting Panel` in the `SUBTITLES` tab that are tied to the mpv subtitle visibility feature. See issue #4235 for screenshots of the changes.

This proposed implementation is in response to the issue #4235 which originated out of issue #4234. I missed that this has come up in the past in issue #2856 with a draft PR #3053. There was even discussion of the problem the mpv feature causes for people that accidentally trigger it.

@WowbaggersLiquidLunch, @unique-username313, the current proposed changes are not as expansive as had been proposed in the past. This PR just provides a GUI for the mpv feature. Critical review comments are welcome.

**Comment by low-batt** [comment]
Rebased with `develop` and fixed merge conflicts.

**Pull request merged**
