### PR TITLE
Add an HDR killswitch in the preferences

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #3808.

---

**Description:**
Since this contains mostly xib changes, redo instead of cherrypicking.
Remake of https://github.com/iina-plus/iina/commit/0cae12493370e2f7d8c59ae007bfaabe4f0b99c3

### CODE REVIEW

**Comment by low-batt** [comment]
I've pulled this PR locally. I've disabled the new HDR preference. IINA is still enabling HDR for the file I'm testing with. Restarting IINA did not help. Investigating...

**Review by low-batt — CHANGES_REQUESTED** [review]
issue-3808

The new preferences button needs to be bound to the setting in user defaults as can be seen was done for the ICC button shown in the screen shot above. I already was going to ask the other developers how you get Xcode to make this binding.  The usual ctrl-click method was not working for me. Anyway this is why the new setting is not working. To see this all you have to do is uncheck the button and restart. The HDR enabled button will be checked again since the value was not stored in user defaults due to the missing binding.

**Comment by low-batt** [comment]
Took me hours to figure out how you directly bind to user defaults in the XIB. All the posts I found on the web provided instructions for binding using code, not directly in the XIB. I finally found the correct place to do this in Xcode.

I tested and when the new preference was disabled IINA did not enable HDR for the HDR video I was testing with.

**Comment by uiryuu** [comment]
@low-batt My bad completely forgetting adding the binding...

**Pull request merged**
