### PR TITLE
Fix format PopupButton again.

### PR DESCRIPTION
**Pull request by xjbeta**
- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #2642 .

---

**Description:**
Find the missing "show screenshot folder in Finder" button.

### CODE REVIEW

**Comment by hazarek** [comment]
is this about the yellow drop-down menu below? i can't click yellow zone. i can click on a thin line zone at the bottom.
cap

**Comment by xjbeta** [comment]
The 'path' label covers this button.
9B843DBF-C4E0-49FB-BB7B-309D98F799C4

**Comment by hazarek** [comment]
i know, Why does the title say "PopupButton"? will this problem be fixed?

**Comment by alejx** [comment]
@xjbeta Why didn't the previous work? I believe I tested that before. Anyway, will merge locally.

**Comment by xjbeta** [comment]
#2642 reverted by lhc.
Because the "show screenshot folder in Finder" button disappeared.

**Pull request closed without merging**
