### PR TITLE
Turkish Translation Update

### PR DESCRIPTION
**Pull request by hazarek**
**Description:**
Turkish Translation Update

### CODE REVIEW

**Comment by alejx** [comment]
Can you reset all the file permission changes?

**Comment by alejx** [comment]
Translations for `PrefutilsViewController`, `OpenURLWindowController`, `MiniPlayerWindowController`, and `PreferenceWindowController` are missing. It would be great if you can add them in this PR.

**Comment by alejx** [comment]
> "alert.config.cannot_create" = "Yapılandırma (config file) dosyası oluşturulamıyor!";
> "alert.config.cannot_create" = "Cannot create config file!\n%@";

Tho not in this PR, can you help to add %@ at the end of the translation?

Anyway, great work overall, and thanks for contributing IINA!

**Comment by hazarek** [comment]
hi @alejx 
> In `Localizable.strings`:
> 
> > "alert.config.cannot_create" = "Yapılandırma (config file) dosyası oluşturulamıyor!";
> > "alert.config.cannot_create" = "Cannot create config file!\n%@";
> 
> Tho not in this PR, can you help to add %@ at the end of the translation?
> 
> Anyway, great work overall, and thanks for contributing IINA!

I don't know how to edit the pull request. I'm a noob. Corrected line`"alert.config.cannot_create" = "Yapılandırma dosyası oluşturulamıyor!\n%@";`

> Can you reset all the file permission changes?

what file permissions? and how?

> Translations for PrefutilsViewController, OpenURLWindowController, MiniPlayerWindowController, and PreferenceWindowController are missing. It would be great if you can add them in this PR.

I did the translation using the IINA Translation Utility. I'll make another update after merge.

**Comment by alejx** [comment]
Alright, fix the issues mentioned above and merged locally. You can make another PR forking against the lastest develop branch. Thanks.

**Comment by hazarek** [comment]
After waiting for months? Forget it. Your iina management is disgraceful.

**Comment by HarukaMa** [comment]
@hazarek LOL

**Comment by lhc70000** [comment]
Hi @hazarek,

IINA was initially started as a personal project, and the development is based loosely on individual contributors. We even don't have a team or product manager. Please note that single contributor's words can't represent the project as a whole.

I understand your discontent. The project has been stagnated in the previous few months because I was busy, and I sincerely apologize for that. Now that we are resuming the development, we will address the project management problem. I will try my best to incorporate existing pull requests without forcing contributors to redo their work. Thanks again for your contribution.

**Pull request closed without merging**
