### PR TITLE
More RTL related fixes on OSC

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4946 and #4878 .

---

**Description:**
This PR
- Revert back 1 previous commit in favor of a more correct fix
- Fix DurationDisplayTextField flipped when having minus sign in RTL #4946
- Make the entire layout of the OSC reverse (as per https://github.com/iina/iina/issues/4878#issuecomment-2067835237)
- The directions of arrows of the media control are fixed (remaining issue in #4878)
- Fix the browser extension layout and the flipped the image #4950

Floating OSC:
image

Top/bottom OSC:
image

Please try out @ShlomoCode, and if there're still OSC related issues or I have messed up anything, please report here so that I can quickly fix them.

### CODE REVIEW

**Comment by ShlomoCode** [comment]
The OSC looks really good! It seems to fix all major issues. Please give me some time to look if there is anything missed.
In the meantime I noticed that the PIP button points in the correct direction (to left) but the popup actually opens on the right side:
CleanShot 2024-05-29 at 05 50 21

**Comment by low-batt** [comment]
@uiryuu The reason why I did not change this initially is because for whatever reason Quicktime does not change the location of the volume as seen here with language set to Hebrew:
quicktime

The button in the PiP window also does not flip with Quicktime:
pip

I don't think IINA can do anything about that as we are just using what the system provides.

**Comment by ShlomoCode** [comment]
> The button in the PiP window also does not flip with Quicktime:

It doesn't look like something intentional, note that the arrows are pointing in random directions... it seems Apple just didn't pay attention to that aspect

https://github.com/iina/iina/assets/78599753/5aa6f73d-fd12-4e80-902a-b020d35f7519

**Comment by ShlomoCode** [comment]
> I don't think IINA can do anything about that as we are just using what the system provides.

The icon **inside** the PIP doesn't matter that much, what matters is the location where it opens, can't you control that? 
Apple's behavior (Safari/QT) is funny - they open the PIP in the **upper corner** of the screen (see my video)...
by the way, I think that's why that it is impossible to learn from them about changing the position of the buttons

**Comment by uiryuu** [comment]
I pushed another commit to fix the browser extension layout and the flipped the image.
telegram-cloud-photo-size-5-6248923411770358876-x

**Comment by ShlomoCode** [comment]
Now I understand that **MacOS opens PIP in the last place where PIP was open** - that is, if you activated PIP in Safari and manually dragged it to a certain corner, then closed it and activated PIP in IINA, it will open in the place where you placed the previous PIP.
Wow, it's getting too complicated to know what the default is...

If so, and if IINA cannot control the MacOS bug of the direction of the arrow inside the PIP not pointing towards the window, the current situation (https://github.com/iina/iina/commit/d6a05e32ba3624975f16fc63bf699545fccd528a) seems fine to me. Sorry for the confusion I caused

**Comment by ShlomoCode** [comment]
> I pushed another commit to fix the browser extension layout and the flipped the image. 

notice that the icon has changed to fill style (maybe you changed it on purpose)

**Comment by uiryuu** [comment]
I did change it intentionally. We used system template previously, however it's very hard to flip for RTL language, so I just used the image from our own assets. Hopefully that wouldn't cause any problem...

**Comment by low-batt** [comment]
IINA is using `PIPViewController`, which is private and not documented, so not easy to control.

**Review by low-batt — APPROVED** [review]
Changes look good to me.

**Comment by lhc70000** [comment]
I just checked that Xcode can correctly mirror the newly added `forward` and `backward` icons.

@uiryuu Please update the last commit to set the icons as "Let to right, mirrors". No new outlets or code should be needed (force push if possible).

**Pull request merged**
