### PR TITLE
Update Localizable.strings for Polish language

### PR DESCRIPTION
**Pull request by igorwojda**
@Greenek please take a look

### CODE REVIEW

**Comment by alejx** [comment]
Hi, could you help to complete current pl localization? You can find missing strings by using our [utility](https://github.com/iina/iina-translation-utility/releases).

**Comment by igorwojda** [comment]
@alejx can you drop me some info on how to use this utility?

**Comment by Greenek** [comment]
Sorry guys, but currently I suffer from a lack of time, so I can't help you with translation :(

**Comment by alejx** [comment]
@igorwojda 
https://github.com/iina/iina/wiki/Translation#3-check-your-translation-automatically
https://github.com/iina/iina-translation-utility/blob/master/README.md
You can try to follow these pages. Feel free to poke me if you have other questions.

**Comment by bdolewski** [comment]
I saw that you still lacking plenty of translations for Polish language so I've added next PR https://github.com/iina/iina/pull/2500 but this should be merged before.

**Comment by igorwojda** [comment]
Sorry guys didn't have time to do it, but my PR together with #2500 provides proper polish translations.

**Comment by bdolewski** [comment]
@Greenek @alejx how can we proceed with this PR and mine at #2500 ? Seriously guys, this is submitted 6 months ago.

**Pull request merged**
