### PR TITLE
Patch minimum macOS version back to 10.11

### PR DESCRIPTION
**Pull request by saagarjha**
- [X] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [ ] This implements/fixes issue #.

---

**Description:**
Add some support back for Mac OS X 10.11.

### CODE REVIEW

**Comment by low-batt** [comment]
Clean build failed for me:
```text
vtool error: /Users/low-batt/Library/Developer/Xcode/DerivedData/iina-caydzgleiqupoxbtitkkfadxksfs/Build/Products/Debug/IINA.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle: can't open file: No such file or directory
```

Checking that directory showed Xcode had not copied Sparkle into Frameworks yet.

Maybe need to specify some input files in the new build phase to get Xcode to run it at the correct time?

**Comment by low-batt** [comment]
Also could not find patch_version.sh in the Xcode project.

**Comment by low-batt** [comment]
I fought with Xcode a bunch. I was unable to get Xcode to run the script after it copies Sparkle to the build directory. Trying to add dependencies to force Xcode to do it caused Xcode to report a build cycle. I think the patch script has to be run as a post build action. I tried doing that and the build worked. But the resulting application has code signing issues. This is the crash:
```text
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
Referenced from: <0682E508-AA5F-3FE2-9E64-C3B9F0B28601> /Users/USER/Library/Developer/Xcode/DerivedData/iina-caydzgleiqupoxbtitkkfadxksfs/Build/Products/Debug/IINA.app/Contents/MacOS/IINA
Reason: tried: '/usr/lib/swift/Sparkle.framework/Versions/B/Sparkle' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/low-batt/Library/Developer/Xcode/DerivedData/iina-caydzgleiqupoxbtitkkfadxksfs/Build/Products/Debug/IINA.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <BAA801DB-601E-35F9-BC9E-E91214AE7EDB> '/Users/low-batt/Library/Developer/Xcode/DerivedData/iina-caydzgleiqupoxbtitkkfadxksfs/Build/Products/Debug/IINA.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/S
(terminated at launch; ignore backtrace) 
```

**Comment by lhc70000** [comment]
@low-batt This also happens when I try to sign Sparkle building the releases. I have to comment it out, build it once, then uncomment and build again. Seems that the Sparkle binary is copied after the run script phase.

**Comment by low-batt** [comment]
I got it to work using a post build action and changing the way the script code signs:
```bash
#!/bin/sh

set -eux

patch_binary() {
	vtool -set-version-min macos "$_MACOSX_DEPLOYMENT_TARGET" "$SDK_VERSION" "$2" -output "$2"
	codesign --force --sign - -o runtime --timestamp\=none "$1" -o runtime "$2"
}

patch_binary '--preserve-metadata\=identifier,entitlements,flags' "$BUILT_PRODUCTS_DIR/$FRAMEWORKS_FOLDER_PATH/Sparkle.framework/Versions/B/Sparkle"
patch_binary "$DERIVED_FILES_DIR/IINA.app.xcent" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_PATH"
```

Needs more work as post build actions are also run for a clean, so when you clean this script fails. Need some checks for file exits unless there is a way to determine you are being run after a clean.

**Comment by saagarjha** [comment]
Closing this for now, I think this needs some more thought.

**Pull request closed without merging**
