### PR TITLE
Fix RTL language causes OSC to malfunction, #4878

### LINKED ISSUE #4878: RTL language causes OSC to malfunction
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.4 + PR #4922

**Expected behavior:**
The on screen controller works properly with right to left languages such as Arabic and Hebrew.

**Actual behavior:**
Currently IINA does not support any right to left languages. However PR #4922 enables Hebrew. If you build IINA with that pull request and set Hebrew as the language then the slider in the OSC malfunctions. When you click on the slider the knob does not move to where the cursor is. The A-B Loop knobs can not be dragged. If you hover over the slider the thumbnail preview shown is not for the correct position in the video. Some images on the OSC point in the wrong direction.

These problems were reported by @ShlomoCode in issue #4776. As that issue reports quite a few RTL related problems I have created this issue that focuses on the OSC problem due to the malfunctioning behavior of the slider.

**Steps to reproduce:**
- Open the IINA project in Xcode
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Start playing a video
- Click on various places in the OSC slider
- Notice the knob moves the the wrong place

Or you can build with PR #4922 and set your language to Hebrew.

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Add initializers to `TimeLabelOverflowedStackView`, `TimeLabelOverflowedView` and `TouchBarPlaySliderCell` that set `userInterfaceLayoutDirection` to be `leftToRight`
- Change `MainWindowController.windowDidLoad` to set the `userInterfaceLayoutDirection` property of `fragControlView` and `oscFloatingTopView` to be `leftToRight`
- Change constraints from leading/trailing to left/right for several OSC components to prevent them from moving when a RTL language is used
- Change `MainWindowController` methods `mouseDown` and `mouseDragged` to take into account the `userInterfaceLayoutDirection` setting during playlist resizing
- Change `ControlBarView.mouseDragged` to take into account the `userInterfaceLayoutDirection` setting when repositioning the floating OSC
- Rename the play property in the `Constants` struct to be `blackRightPointingTriangle`
- Add a `blackLeftPointingTriangle` property to the `Constants` struct
- Change `PlaylistViewController.tableView` to use a right or left arrow based on the `userInterfaceLayoutDirection` setting
- Change the language-direction of the pip and volume related icons and the `playlist` icon from `Fixed` to `Left to Right, Mirrors`

This adjusts IINA's behavior to match Apple's guidance that video controls and timeline indicators should not flip in a right-to-left language. Other controls, such as the volume control and the pip and playlist buttons are flipped for RTL languages.

This also corrects problems dragging the floating OSC and resizing the playlist when a right to left language is configured.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4878.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
Found another problem. Dragging the floating OSC is messed up. Putting this in draft mode until I can fix that.

**Comment by uiryuu** [comment]
The changes look harmless. If @ShlomoCode agrees to all the changes, then we can merge.

**Comment by ShlomoCode** [comment]
I've actually been using a local build of these changes for a few weeks now, and it's working great. One thing I feel uncomfortable with is the order of the custom buttons, discussed in this comment and below and was not decided: https://github.com/iina/iina/issues/4878#issuecomment-2065535646

~~Another little thing is this icon:
CleanShot 2024-05-24 at 07 31 25@2x
Its direction is determined by the language of the application, but it should be determined by the language of the operating system, because it is the **system** language that determines the PIP location. 
That is, in case the system language is RTL, even if the language defined for the application is LTR, the PIP will open on the left side, and vice versa.~~

**Comment by ShlomoCode** [comment]
🤔

**Comment by uiryuu** [comment]
@ShlomoCode Please try the latest version on `enable-he` branch and report anything looks incorrect and file an issue.

Screenshot 2024-05-26 at 9 36 54

The custom buttons are on the left now.

As for the PIP button direction problem, please file another issue for that, thank you!

**Comment by ShlomoCode** [comment]
> The custom buttons are on the left now.

Not for me 🤔
CleanShot 2024-05-29 at 02 53 54@2x
Even with the Hebrew **system** language.

**Comment by ShlomoCode** [comment]
Should close as resolved

**Pull request merged**
