### PR TITLE
Hide main window when entering Picture in Picture

### PR DESCRIPTION
**Pull request by LEoREo2247**
- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #2147.

---

**Description:**

This PR will add ability to hide main window when entering Picture in Picture if window is not in fullscreen mode.
I looked in to it and I noticed that implementation is quite simple.
It doesn't require specification to re-show window when going back from PiP as PiP seems to be doing that already.
I also added option to enable/disable this behavior, but this may not needed. It depends on how you all thinks.

### CODE REVIEW

**Comment by anohren** [comment]
So, should the discussion be held here? If yes: what were the reasonings for minimizing the window, raising it or whatever? I can see the point of minimizing the window since that's effectively hiding the window, but that's pretty much it. 

If those suggestions are alternatives to this one, then they fit quite naturally in here.

Sounds kind of weird to move core functionality like PiP to a plugin though.

**Comment by saagarjha** [comment]
The core PIP functionality (e.g. actually entering/exiting PIP) likely cannot be a plugin, and will remain as-is. The question is allowing users to customize "reactions" to these events, so they they can e.g. minimize the main window when entering picture-in-picture, or close it, etc. So my question is 1. whether we should have this customization point, 2. whether we should say have a preference that lists some commonly requested actions and performs that when PIP is invoked, or 3. not have a preference at all, but allow plugins to customize this behavior.

**Comment by anohren** [comment]
I suspected that that was your intention. However, since, as you say, PiP will remain a core functionality it needs to have a sensible default behavior regardless of whether this will be made a customization point and regardless of whether any such plugins are installed.

If I'm not mistaken, this PR is mostly about implementing the most sensible default behavior. Perhaps it should be split up so that the discussion about if/how to make this customizable can continue independently.


Unless of course that your suggestion is to implement default behavior like this as an official plugin. Sounds a bit overkill, but perhaps that's been the plan all along.

**Comment by LEoREo2247** [comment]
Alright, I think that is pretty neat. I can try implementing that if anyone else wouldn't.

**Comment by LEoREo2247** [comment]
So I've added the options that saagarjha listed. I need someone to check if there is any problem or a flaw.

**Comment by saagarjha** [comment]
Great job, @LEoREo2247! There's still some jankiness with the transition, but that's my problem, not yours; I'll look into whether this can be fixed later.

**Pull request merged**
