### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [ ] This implements/fixes issue #.

---

**Description:**

Found few misspellings.

Please consider using https://github.com/crate-ci/typos

### CODE REVIEW

**Comment by uiryuu** [comment]
Thanks for your suggestion, will consider to add this to the CI.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by szepeviktor** [comment]
> to add this to the CI.

`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "deps/",
    "iina.xcodeproj/",
    "**/*.strings",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bBig Sur\\b",
    '(firstItem|secondItem|id|destination|headerView)="[0-9A-Za-z]+-[0-9A-Za-z]+-[0-9A-Za-z]+"',
    'apiKey = "[^"]+"',
    "V\\[alue\\]",
    "ba!",
]

[default.extend-words]
"abitrate" = "abitrate"
"splitted" = "splitted"

[default.extend-identifiers]
"caf" = "caf"
"iy" = "iy"
"reloadSavedIINAfilters" = "reloadSavedIINAfilters"
"ScreenshootOSDView" = "ScreenshootOSDView"
"tak" = "tak"
"videoParamsMaxCll" = "videoParamsMaxCll"
```

**Comment by uiryuu** [comment]
Can you file another PR to add [crate-ci/typos](https://github.com/crate-ci/typos) to the existing CI?

**Pull request merged**
