### PR TITLE
feat: enable hebrew locale

### PR DESCRIPTION
**Pull request by ShlomoCode**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [ ] This implements/fixes issue #.

---

**Description:**

The Hebrew translation is complete (100% of the strings), this PR activates the language

### CODE REVIEW

**Comment by low-batt** [comment]
Added issue #4867 for tracking.

**Review by low-batt — APPROVED** [review]
Pulled PR, built and tested.

With the translations currently in the `develop` branch I found only a few strings that were missing translations. We should upgrade `develop` with the latest translations and check these again. I would not block enabling the Hebrew locale on these few missing translations. So this PR looks good to me.

**Comment by low-batt** [comment]
I tested by setting the language for just IINA. I noticed the window buttons were still on the left side of the window and conflicts with the scroll bar. Does this happen for you as well?

issue-4867-window

**Comment by ShlomoCode** [comment]
@low-batt Yes, this is the second RTL bug I reported at https://github.com/iina/iina/issues/4776
Edit: now I notice that this only happens when the system language is LTR, and a RTL language is set for the application in the system settings. when the system language is RTL it is normal, because the buttons are located on the right side.
but this such a mix is quite a common case.

**Comment by low-batt** [comment]
I replied to issue #4776.

**Comment by ShlomoCode** [comment]
Sorry, I forgot about this PR and deleted my fork. Is there a way to reopen it?

**Comment by ShlomoCode** [comment]
Sorry, I forgot about this PR and deleted my fork. Is there a way to reopen it?

**Comment by ShlomoCode** [comment]
Sorry, I forgot about this PR and deleted my fork. Is there a way to reopen it?

**Comment by ShlomoCode** [comment]
?

**Comment by low-batt** [comment]
See: [Restoring a deleted repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository)

If all else fails I should have a local copy of this PR branch on my machine. Caught me busy. I should be working on IINA later today.

**Comment by ShlomoCode** [comment]
>If your repository was part of a fork network, it cannot be restored unless every other repository in the network is deleted or has been detached from the network.

and in my settings:
>You can only restore repositories that are not forks, or have not been forked

I have the code on my local computer, I'll just open PR again.

**Comment by low-batt** [comment]
Sounds good. I see #4922 is the replacement PR.

**Comment by ShlomoCode** [comment]
Yes. It should be associated with #4867 (instead of the closed PR)

**Comment by low-batt** [comment]
I fixed the stale reference. I will go through my issues tomorrow and update the stale references in them.

**Pull request closed without merging**
