### PR TITLE
Improve PIP

### PR DESCRIPTION
**Pull request by saagarjha**
- [X] This change has been discussed with the author.
- [X] It implements / fixes issue #735, #879.

---

I've gone through and fixed some PIP bugs as well as simplified the related code.

### CODE REVIEW

**Comment by saagarjha** [comment]
@lhc70000 If you're running macOS Sierra would you mind testing this out?

**Comment by lhc70000** [comment]
@saagarjha 👌

**Comment by lhc70000** [comment]
LGTM. Could you also fix #511?

**Comment by alejx** [comment]
screen shot 2017-07-23 at 12 37 02 pm
Thumbnail preview should be disabled in picture in picture.

**Comment by alejx** [comment]
screen shot 2017-07-23 at 12 40 03 pm
It would be better if we can handle this strange box for OSDs in pip.

**Comment by lhc70000** [comment]
@alejx Let's discuss in #350 or #380.

Perhaps after adding the "Music mode", we can switch to that mode when entered PIP.

**Comment by saagarjha** [comment]
@lhc70000 Done.
@alejx This might be a bug with `NSVisualEffectView`–if so, there's not much we can do other than file a radar.

**Pull request merged**
