### PR TITLE
update zh-Hans

### PR DESCRIPTION
**Pull request by L1cardo**
- [No] This change has been discussed with the author.
- [No] It implements / fixes issue #.

---

**Description:** update zh-Hans

### CODE REVIEW

**Comment by HarukaMa** [comment]
Sorry but this will not count you as a contributor.

**Comment by HarukaMa** [comment]
Funny that you don't even know that how this software looks like under current Simp. Chinese localization then you just went to change some irrelevant strings.

That's really intriguing.

**Comment by inflation** [comment]
都是千年的狐狸，在这玩什么聊斋¿

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by L1cardo** [comment]
Fine !
You're right!

**Comment by L1cardo** [comment]
我tm 学医  混个 contributor 有啥意思？  你说说看

**Comment by L1cardo** [comment]
我就是喜欢汉化，我怎么知道这个软件开发者竟然是这个唯利是图的中国人！  shame on you

**Comment by HarukaMa** [comment]
Reported abuse: personal attacking.

Have a good day.

**Pull request closed without merging**
