### PR TITLE
Enable dragging URL into video view.

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] This change has been discussed with the author.
- [x] It implements issue #294 (part 1).
- [ ] It implements issue #294 (part 2).

---

**Description:**

Did not rebase to the latest commit (06d6d9b) because it will crash after opening
files.

### CODE REVIEW

**Comment by lhc70000** [comment]
Any updates / ready for merge?

**Comment by alejx** [comment]
Do you think it is necessary to treat strings that users drop into as a URL?

**Comment by lhc70000** [comment]
> Do you think it is necessary to treat strings that users drop into as a URL?

interesting... let's implement it. e.g.:

1. Check for protocol like `http://` or any other that supported by mpv; load url if true
2. If no protocol presented, check whether string is a web url by a RegExp; try to load if true
3. (Check whether it's a file path?)

**Comment by alejx** [comment]
> 2. If no protocol presented, check whether string is a web url by a **RegExp**;

Which RegExp would you like to use? I found there are many different RegExp to judge URLs.

> 3. (Check whether it's a file path?)

I don't think check whether string is a file path is necessary. Unlike windows users, macOS users cannot get files' path very easily.

**Comment by lhc70000** [comment]
`@^(https?|ftp)://[^\s/$.?#].[^\s]*$@iS` should be OK.

**Pull request merged**
