### PR TITLE
Fix RTL language causes overlapping in settings, #4888

### LINKED ISSUE #4888: RTL language causes overlapping in subtitle settings
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.4 + PR #4922

**Expected behavior:**
UI components do not overlap with right to left languages such as Arabic and Hebrew.

**Actual behavior:**
Currently IINA does not support any right to left languages. However PR #4922 enables Hebrew. If you build IINA with that pull request and set Hebrew as the language then the color wells on the `Subtitle` tab of IINA's settings overlap the labels for the control. Also, if on the `UI` tab in the `On Screen Display` section the  `Display time and battery info when in full screen` setting is enabled then the text giving the battery state overlaps with the battery icon.

These problems were reported by @ShlomoCode in issue #4776. As that issue reports quite a few RTL related problems I have created this issue to focus just on these two problems.

**Steps to reproduce:**
- Open the IINA project in Xcode
- Under the `Product` menu open the `Scheme` menu and select `Edit Scheme…`  
- Click on the `Options` tab
- Scroll down to the `App Language` setting
- In the pull down select `Right-to-Left Pseudolanguage` near the end of the list
- Start IINA running under Xcode
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
- On the left side of the panel click on `Subtitle`
- Notice in the `Text Subtitles` section the labels overlapping with the color wells.

Or you can build with PR #4922 and set your language to Hebrew.

- [x] MPV does not have this problem.

mpv does not support localization.

**How often does this happen?**
Every time.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Correct the constraints in `PrefSubViewController.xib`
- Change the `Mirror` setting to `Never` on the color wells in the XIB
- Change the language-direction of the battery icon from `Fixed` to `Left to Right, Mirrors`

This corrects a problem with color wells overlapping their labels on the Subtitle tab of IINA's settings. This also changes the battery icon shown in full screen mode to flip in a RTL language correcting another overlapping problem.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4888.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
See issue #4776 for a screenshot of the RTL overlaps.

IINA 1.3.4:
released


With the changes in this PR…
fixed-en
fixed-he

**Comment by ShlomoCode** [comment]
I responded to the associated issue. (was it correct to respond here?)

**Comment by low-batt** [comment]
The issue with the malformed color wells in RTL has been fixed:
he-sub-settings

But the mirroring applied by AppKit to the battery icon results in a blurry image:
he-battery

@lhc70000 will be generating a reversed battery image. I will then add it to the existing battery icon image set as a `Right to Left` image.

I have set this to be a draft until the blurry battery problem is corrected.

**Comment by ShlomoCode** [comment]
It seems to me that a perfect inversion is like this:
CleanShot 2024-04-26 at 03 17 33
Instead of:
CleanShot 2024-04-26 at 03 24 37@2x

**Comment by ShlomoCode** [comment]
> @lhc70000 will be generating a reversed battery image. I will then add it to the existing battery icon image set as a `Right to Left` image.

I mirrored the PDF from [here](https://github.com/iina/iina/blob/develop/iina/Assets.xcassets/Icons/battery.imageset/battery.pdf) simply using Apple Preview, it seems to keep full quality.
[battery.pdf](https://github.com/iina/iina/files/15124304/battery.pdf)
CleanShot 2024-04-26 at 04 47 27

**Comment by low-batt** [comment]
Thanks! But… been there, done that. It all looked good in Preview and in Xcode, but at runtime the flipped battery looks just like the original battery. It faces the wrong direction. This is because Apple Preview does not remake the PDF, it adds a rotate tag to it. Seems AppKit does not support the tag.

At least I think that is what was happening. Did I miss something?

**Comment by ShlomoCode** [comment]
Yes, it looks like you're right :(
BTW recreating the file with ImageMagick helps, but I couldn't find the exact command to keep the file at full quality

**Comment by low-batt** [comment]
Took me a while to figure out what was happening. Since Xcode showed the reversed PDF correctly I was thinking the code was not picking the RTL version of the battery.

@lhc70000 created the battery icon. He will be able to provide a flipped one that matches the existing one.

**Comment by ShlomoCode** [comment]
@low-batt What do you think about [this](https://github.com/iina/iina/pull/4889#issuecomment-2078390691)?

**Comment by low-batt** [comment]
Oh. I missed that detail. My thoughts are that IINA should not try to change this. This is the behavior Apple supplies for an AppKit [NSColorWell](https://developer.apple.com/documentation/appkit/nscolorwell). If this is incorrect then Apple needs to fix it. Just to be sure I ran the little test program I wrote while working on this and confirmed this is the Apple supplied RTL behavior for this component.

**Comment by lhc70000** [comment]
Added the mirrored battery icon.

**Comment by low-batt** [comment]
Thanks! The new icon looks good. However I am going to simplify the change. There is no need for the code in `MainWindowController`. The easier way to do this is to reconfigure the icon to select the correct image automatically. I will work on that change now.

**Comment by low-batt** [comment]
The constraint for the text within the battery icon is correct for LTR and a little off for RTL. I will be fixing that, but gotten too late tonight. I have to help afriend tomorrow, so may not get to it until Saturday. Leaving this as a draft for now.

To get an icon to have separate LTR and RTL images change the direction to `Both` as I shown below. Once that change is made a location for a RTL image appears and you can just drag & drop the RTL image to it.
Both

**Comment by low-batt** [comment]
LTR:
LTR

RTL:
RTL

I think this one is ready for review

**Comment by ShlomoCode** [comment]
@low-batt Good job!
It seems that the vertical balance is normal in LTR:
SCR-20240526-euru

But in RTL there is much more space at the top:
SCR-20240526-eugw

In addition, the LTR version is still slightly sharper
CleanShot 2024-05-26 at 05 06 37@2x
CleanShot 2024-05-26 at 05 07 50@2x

**Comment by low-batt** [comment]
I had noticed the alignment seemed just a bit off. On the fuzzy aspect I see this:
```text
low-batt@gag battery.imageset (enable-he $%=)$ pwd
/Users/low-batt/Documents/builds/iina-official/iina/iina/Assets.xcassets/Icons/battery.imageset
low-batt@gag battery.imageset (enable-he $%=)$ ls -lh
total 96
-rw-r--r--  1 low-batt  staff   397B May 25 23:55 Contents.json
-rw-r--r--  1 low-batt  staff   2.9K May 25 23:55 battery-rtl.pdf
-rw-r--r--  1 low-batt  staff    38K Apr 24 22:47 battery.pdf
low-batt@gag battery.imageset (enable-he $%=)$ 
```

The sharp image is 38K bytes. The fuzzy reversed image is only 2.9K bytes.

We need @lhc70000 to generate a sharper image. This seems like the same problem I was having generating a reversed image. The tools I tried all shrank the file and made it fuzzy. I don't know how the original file was created.

**Comment by ShlomoCode** [comment]
BTW, I did the alignment test I uploaded using the free app [Shottr](https://shottr.cc)

**Comment by low-batt** [comment]
`Shottr` looks nice. I obtained an updated sharp image from @lhc70000 and have pushed a commit to the `enable-he` branch. It looked like that solved the alignment problem as well. Although it is late here, so everything is starting to look blurry to me right now.

**Comment by ShlomoCode** [comment]
@low-batt It's still less sharp than the LTR version, but it's already sharp enough that it doesn't bother me, so I don't know how important it is to do another round.
One remaining point is that the text inside the battery should be right/center aligned but not left
CleanShot 2024-05-29 at 03 07 51@2x

**Pull request merged**
