### PR TITLE
Added controls to QuickSettingsPanel to control second subtitles position and delay

### LINKED ISSUE #4009: Make the second subtitle position adjustable
Make the second subtitle position adjustable.

IINA currently defaults the second subtitle position to the top.

This feature should be added so that the second subtitle can be adjusted to a more readable position. Currently the second subtitle isn't useful if it defaults to the top.

Daum PotPlayer has the functionality to adjust the second subtitle position.

### LINKED ISSUE #4524: Separate control for secondary subtitle delay
**What you want IINA to do:**
Provide a way to separately control the delay for the primary and secondary subtitles. This should include a way to keep the delays in sync to avoid forcing users to change two sliders when both subtitles need the same delay applied.

This feature request comes from a Telegram user in the IINA group chat.

**What IINA does currently:**
A single slider on the subtitles panel controls the delay for both the primary and secondary subtitles.

**Why you think this should be added:**
This ability has been requested in mpv issue https://github.com/mpv-player/mpv/issues/2629. There is a pending implementation in mpv PR https://github.com/mpv-player/mpv/pull/11689.

This IINA issue tracks the need to update IINA once mpv has added this feature.

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issues:
  - #4009 
  - #4524

---

**Description:**
mpv recently added `secondary-sub-pos` and `secondary-sub-delay` options, which enables user to control position and delay separately for primary subtitles and secondary subtitles. This PR implement these two new options by added a SegmentedControl in the QuickSettingsPanel to let user choose from primary or secondary subtitles when adjusting subtitle position and delay.

Note that the other options (e.g. `sub-scale`) apply to both primary subtitles and secondary subtitles, so they are outside of the NSBox.

https://github.com/iina/iina/assets/20237141/53b9084b-4433-487d-a080-4aab0e33429c

The layout of the subtitle tab of the QuickSettingPanel also got changed to better illustrate the new feature (before -> after):

image image

### CODE REVIEW

**Review by low-batt — APPROVED** [review]
I really like the segmented controls. They look great and should be easy for users to understand.

I pushed a commit to add the segmented control label names to `QuickSettingViewController.strings`. With that I think this can be merged as is. The next step is to add the corresponding OSD messages for secondary sub position and delay changing like we have for the primary sub.

Need to merge the simple PR #5019 that adds a couple of missing secondary options to `watch-later-options`.

"Secondary" is the proper term. We should consider changing the menu items that use the term "Second".

And of course subtitle preferences needs some enhancement in this area.

To test this I used the YouTube video [10 Minute Timer (count-up stopwatch)](https://www.youtube.com/watch?v=pHvP71rwYAc) with these two subtitle files:
[sub-1.srt.txt](https://github.com/user-attachments/files/15960731/sub-1.srt.txt)
[sub-2.srt.txt](https://github.com/user-attachments/files/15960734/sub-2.srt.txt)


I checked RTL:
delay


The messed up label at the end of the delay slider is issue #4895 / PR #4896. That PR is in draft mode because it needs a UI expert to take over from me and solve the last little issue shown in the screenshots in [this comment](https://github.com/iina/iina/issues/4895#issuecomment-2092080131).

**Comment by low-batt** [comment]
One more related topic. The [secondary-sub-pos](https://mpv.io/manual/stable/#options-secondary-sub-pos), like [sub-pos](https://mpv.io/manual/stable/#options-sub-pos) has a range of 0% to 150%. IINA tries to limit it to 100%. I believe this is because unlike mpv IINA ties the window size to the video size. I know removing that restriction has been reported in multiple issues, for example #4712. @svobs has looked into this. Anyway, I said "tries" because if you keep pressing the `T` key you can go past 100%. Given how IINA does not provide a way to have a black border you could move subtitles into I think it makes sense to restrict the sliders to 100%. I only mention this as a reminder of another subtitle feature that could be improved.

**Comment by uiryuu** [comment]
> I pushed a commit to add the segmented control label names to QuickSettingViewController.strings. 

Sorry I forgot to do that, and thanks!

> And of course subtitle preferences needs some enhancement in this area.

I was unsure of how to design the UI to add secondary subtitles in, so I didn't include that in this PR.

> "Secondary" is the proper term. We should consider changing the menu items that use the term "Second".

Besides this, I remember I've heard that the word "subtitle" should always be in plural form, is that correct? Should we enforce that (in the future)?

**Comment by low-batt** [comment]
It usually is "subtitles" but not always "subtitles".

It is a "subtitle file" as can be seen in the mpv manual entry for the [sub-file](https://mpv.io/manual/stable/#options-sub-file) option:
> **--sub-files=\<file-list>, --sub-file=\<filename>**
>  Add a subtitle file to the list of external subtitles.

It is a "subtitle stream" as can be seen in the mpv manual entry for the [sid](https://mpv.io/manual/stable/#options-sid) option:
> **--sid=<ID|auto|no>**
> Display the subtitle stream specified by \<ID>. auto selects the default, no disables subtitles.

The IINA menu items are about selecting a "subtitle stream".

One label that should be changed is the `Subtitle` tab name in IINA's settings. that should be `Subtitles`, just like the  `Subtitles` tab on the quick settings panel and the  `Subtitles` menu.

**Comment by lhc70000** [comment]
Update the styling and also enabled the macOS 13+ NSColorWell.

**Comment by amoghsrivastava** [comment]
Is this in the latest release? Been waiting for this fix for a while now! ❤️

**Comment by low-batt** [comment]
IINA has been finally working on the long delayed "feature release". This is one of the changes going into that release. This pull request is in the `Merged` state, indicating the review is complete, the changes were approved and merged into the `develop` branch from which the next IINA release will be created. This change is not in the current release of IINA, 1.3.5.

As this next release contains lots of changes considered risky it will use beta releases. We are at this moment working on winding down the changes in preparation of cutting a release. We still have a handful of pull requests to review and merge. Then we will do some more testing before starting on the release process.

There have been many requests for better controls for secondary subtitles. IINA had to wait for the [mpv](https://mpv.io/) project to add additional options for controlling the secondary subtitles. They finally did, allowing IINA to add new UI to access the new abilities.

**Comment by amoghsrivastava** [comment]
Great to know. Thanks @low-batt ! 
I have got the nightly for now. Do you expect any crashes taking place using Nightly? I'm playing a 1080p mp4 file

**Comment by low-batt** [comment]
If you ever encounter a crash running a Nightly build, please report it. Changes are tested and reviewed before being merged into the Nightly build, so there should not be any new crashes. However, it is possible for a mistake to make it through the process. So if you find any sort of regression, a crash, a malfunction, a performance problem, we'd like to know.

**Comment by low-batt** [comment]
This was included in IINA 1.4.0.

**Pull request merged**
