### PR TITLE
Replace showAlert() with showAlertByKey()

### LINKED ISSUE #295: Localize calls to Utility.showAlert
Right now, message is hardcoded. It should be localizable.

### PR DESCRIPTION
**Pull request by inflation**
Fix #295 .

### CODE REVIEW

**Comment by lhc70000** [comment]
Why not `showAlert(byKey:_)` or `showAlert(key:_)`?

**Comment by inflation** [comment]
I'm trying to reserve both methods until most of the code bases are up to date. It's kind like a break change.

**Comment by lhc70000** [comment]
(Unsurprisingly,) conflicted (severely). (my fault)

But why did you delete the English localization file? System won't read the base one as fallback in English environment.

**Comment by inflation** [comment]
Closing due to too many conflicts. Will rewrite a new one.

**Pull request closed without merging**
