### PR TITLE
Add language selection in preference

### PR DESCRIPTION
**Pull request by jh1104**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**
screen shot 2018-11-23 at 2 23 25 am
screen shot 2018-11-23 at 2 23 37 am

### CODE REVIEW

**Comment by flocked** [comment]
Why implementing a language selector? I don't know native Mac apps that have language selectors. If you want to change the language of your apps, the system settings are the right area to change them.

**Comment by rhagodessa** [comment]
@flocked 

I am not good at English, but development tools are easy to use in English.
so my mac system language is English.
however, other apps(media, messenger, etc.) are easy to use in native language.

And VLC also has language selector.

**Comment by alejx** [comment]
I think you can just write defaults to IINA.app in terminal, or you can use [Language Switcher](http://www.tj-hd.co.uk/en-gb/languageswitcher/) to change language for a specific app.

**Comment by rhagodessa** [comment]
@alejx 
Thanks for letting me know🙂
then what i should do? close this pull request?

**Comment by alejx** [comment]
macOS will officially support changing languages for specific apps in macOS 10.15 Catalina.
image
BTW this feature will present in iOS (and iPadOS I guess) as well.

No need to implement it by ourselves, closing.

**Pull request closed without merging**
