### PR TITLE
Key navigation fixes in player window input fields (fixes #3039, #3206)

### LINKED ISSUE #3039: Arrow keys skip time instead of characters when in settings input field
When a medium is playing and you access an input field in the playback settings panel via the gearwheel, the arrow keys still skip time instead of moving the curser in the input field.

**System and IINA version:**
- macOS 10.15.5
- IINA 1.0.7 Build 119

**Expected behavior:**
Pressing the arrow keys inside an input field should move the curser inside it.

**Actual behavior:**
Pressing the curser keys inside a playback-settings input field skips time inside the medium, that's currently playing.

<br>

<br>

**Steps to reproduce:**
1. Start a medium, e.g. a video
2. enter the playback settings panel via the gear
3. klick on an input field (e.g. playback speed)
4. press an arrow key to move the curser

- [ ] MPV does not have this problem.

**How often does this happen?**
Every time you want to move the curser inside an input field

### LINKED ISSUE #3206: Arrow keys in input fields in Quick Settings should not affect playback
When using the arrow keys in any input field in Quick Settings, they affect the playback instead of the cursor in the input field. This is extremely annoying, since you have to move the cursor by mouse, if you want to change what you typed.

**System and IINA version:**

- macOS 11.0.1 (20B29)
- IINA 1.1.1 Build 125

**Expected behavior:**

The arrow keys move the cursor in the input field.

**Actual behavior:**

The arrow keys move the playback position.

**Steps to reproduce:**

1. Open Quick Settings while playing a video.
2. Place your cursor in any input field, for example **Speed**
3. Type something in the input field.
4. Use the arrow keys to move the cursor inside the input field.
5. Observe how the arrow keys change the playback position (for left and right) or volume (for up and down) instead of the cursor position in the input field.

**How often does this happen?**

Always

### PR DESCRIPTION
**Pull request by svobs**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #3039, #3206.

---

**Description:**
1. Adds a check for arrow keys to text input fields, so that they always navigate inside the text instead of activating menu items.
2. Updates all the Quick Settings controls which should never have keyboard focus to refuse first responder status, so that pressing `TAB` or `SHIFT+TAB` in a text field doesn't create an unusable glowing focus ring around one of them.

### CODE REVIEW

**Comment by svobs** [comment]
Didn't realize before but this also fixes arrow key navigation in the download selection pop-over which appears after clicking the `Search Online...` button in the Subtitles Settings sidebar.

**Comment by svobs** [comment]
Pushed another commit which changes the `refusesFirstResponder` property in the `Switch` class to be configurable, instead of hard-coding it to `true`. It was preventing the `Enable advanced settings` switch (IINA > Settings... > Advanced)  from participating in tab navigation...which, uh, only affected my branch, as the official IINA doesn't yet support tab navigation in the Settings window...but it's a more precise fix.

**Comment by svobs** [comment]
Rebased + scaled down the changes so that only the text field issue is now addressed. The fix for table navigation was only halfway there anyway.

**Comment by svobs** [comment]
Rebased to fix merge problems + improved commit msg.

**Comment by uiryuu** [comment]
Thanks!

**Pull request merged**
