### PR TITLE
Fix IINA is not associated with GIF files, #3679

### LINKED ISSUE #3679: IINA is not associated with GIF files
**System and IINA version:**

- macOS 12.3.1
- IINA 1.2.0

**Expected behavior:**
Right clicking a .gif file and selecting "Open With" shows IINA as one of the applications to use to open the file.

**Actual behavior:**
IINA is missing from the list of applications to open the GIF file with.

Short animated GIF files are popular, such as the ones available on the tenor website. In macOS by default the application associated with GIF files is Preview. In macOS 12.3.1 Preview is still unable to play animated GIF files. To play an animated GIF you must use the Finder quicklook feature or right click on the file and select another application. When you right click the menu that comes up does not include IINA even though IINA is able to play animated GIFs. This is because IINA does not register with macOS that it should be associated with GIF files.

**Steps to reproduce:**
Right click in Finder on an animated GIF file and select "Open With".
IINA should be displayed in the list of applications, it is not.

- [ ] MPV does not have this problem.

MPV does have this same problem. But this is still an IINA issue.

**How often does this happen?**
Every time.

I will shortly post a pull request with the required changes to inform macOS that IINA can open GIF files.

### PR DESCRIPTION
**Pull request by low-batt**
The commit in the pull request will:
- Add a document type entry for GIF files to Info.plist
- Add document icons for GIF files as Assets

- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #3679.

---

**Description:**
The changes in the commit associate IINA with GIF files. The document icons are in the latest style required by the Apple HIG. Thank you to @Zabriskije for supplying the icons.

### CODE REVIEW

**Comment by lhc70000** [comment]
I think the graphical elements should be consistent. If updating one document icon, we should remake all of them. I suggest we postpone this change until the next release. We may also want to add some other enhancements for gif files.

**Comment by low-batt** [comment]
On postponing GIF support to consider if other enhancements are needed, sounds good. Let's hold off merging this.

On the document icon issue, a full set of updated document icons are ready. I did not post a PR as it didn't seem appropriate for a bug fix release focused on critical issues. The commit is https://github.com/low-batt/iina/commit/43aeac15a720a43a2b307a0ec90aa30c9cbd2119. See discussion 3670 for details. I think he is right about the current document icons needing to be updated to follow the new HIG requirements.

With the current release plan I'm thinking we should consider including the updated icons as "polish" Have a look at that discussion and see what you think.

**Comment by Mikasa-san** [comment]
Hey do you have any idea why the doc icons doesn't copy to iina app when building it ?

**Comment by low-batt** [comment]
Thanks for entering the issue about that. Unrelated to this PR, a PR was merged that was supposed to update the doc icons. Looks like something went wrong with that. I'm in the middle of another PR at the moment, but will look into the icon problem soon.

**Comment by low-batt** [comment]
Added importing the GIF type entry and rebased with `develop`.

The document icons have been updated, so the new document icon included in this PR now is consistent with the other document icons.

The other issue that was raised is the possibility of adding other enhancements for gif files. Not sure what that would be. I played around with animated GIFs from [tenor](https://tenor.com/). The IINA video controls I tried all worked.

**Review by uiryuu — APPROVED** [review]

**Pull request merged**
