### PR TITLE
OpenSubtitles: fix episode guessing

### PR DESCRIPTION
**Pull request by ark-1**
Includes the fixes for #3907 and #3908, based on the code by @low-batt.

- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issues #3907, #3908.

---

**Description:**
See the corresponding issues.

### CODE REVIEW

**Comment by low-batt** [comment]
Thanks for trying to fix these issues!

I have fixes for these two issues, but I have been intentionally not created a PR to avoid conflicts with the large amount of changes in this area contained in PR #3944. That PR needs to be merged first to avoid merge conflicts. 

I did assign these two issues to myself to let other developers know I would take care of fixing these issues.

Anyway, it is desirable to get PR #3944 merged first before merging any other changing in this area.

**Comment by ark-1** [comment]
Sorry about that, I missed the fact that they were already assigned.
In the issue, you said that creating a PR is held off until the plugin system is merged. I checked that it is, so I presumed there's nothing blocking it.

Actually, I'm not sure I agree with this merge conflict avoidance practice. If we have two PRs, both touching the same area, we can wait until the first one of them is approved and merged, and simply resolve the conflicts in the other one. Usually, for changes this small, this really not a problem. This way the fixes can be delivered as soon as they are ready to be merged. But if we wait until a specific PR (like plugin system in this case) is merged, a simple change (like episode guessing fix) can be delayed needlessly. And if some other PR appears (like 3944), it can be delayed over and over, prolonging the pain of the users (like me 😆 ).

Anyway, please tell me, should I just close this PR and wait for your fixes, or keep it open and wait for these fixes to be merged?

**Comment by low-batt** [comment]
Please keep it open. Missing the assignment is not a problem. Happens. Your efforts are appreciated. 
My comments were more directed @lhc70000 to remind him about PR #3944.

The situation with PR #3944 is special. A form of those changes are in 1.3.0. They were merged into a branch from which 1.3.0 was built. They were not merged into develop because there were lots of changes in this area for the plugin system. So the plan was that after the release we'd get the plugin system merged and I'd deal with preparing a new PR with the equivalent changes compatible with the plugin system. That is what PR #3944 is. So currently develop is missing fixes that are in 1.3.0. That makes getting PR #3944 merged a priority.

You got me to check on PR #3944 and I see I already need to resolve merge conflicts. I will get that done today.

So yes, holding up merging PRs over merge concerns is a problematic practice we hopefully can avoid once we get the develop branch consistent with the 1.3.0 release.

**Comment by ark-1** [comment]
Thank you for your clarifications. I hope this all can be resolved soon!
I'll subscribe to #3944 then :)

**Comment by low-batt** [comment]
The PR we were waiting for, PR #3944 was replaced by PR #3975 which was just merged.
This PR now needs to be rebased with develop and merge conflicts corrected.
Then we can get this one merged.

**Comment by ark-1** [comment]
Done!

**Review by low-batt — APPROVED** [review]
I pulled the PR locally, tested and confirmed this fixes the two issues.
Changes look good to me.

**Comment by lhc70000** [comment]
Merged. Thank you!

**Comment by ark-1** [comment]
Thanks!
Is it by any chance possible to add a `hacktoberfest-accepted` label to this PR?

**Pull request merged**
