### PR TITLE
Show volume popover when scrolling to adjust in miniplayer

### PR DESCRIPTION
**Pull request by alejx**
Ref: #2999, #2191

Co-authored-by: LEoREo2247

- [x] It implements / fixes issue #2999.

@anohren, please take a look at whether this is the correct behavior. Since I almost used the entire @LEoREo2247's code, I also gave them credits on this commit.

### CODE REVIEW

**Comment by lhc70000** [comment]
Is it still needed after #2977?

Personally I think it's a little bit awkward to trigger the popover when scrolling. Although the current icon after #2977 and 0ba3798 doesn't show the precise volume, it gives sufficient visual feedback IMHO.

**Comment by anohren** [comment]
I haven't tried this PR or 2977, but spontaneously: yes, this is still needed.

If you're ok with your trackpad arbitrarily alternating between pixel-perfect scrolling and behaving like a discrete step mouse wheel it might be enough with 3 steps of feedback, but intuitively I don't think anyone wants that. Especially since there are 100 steps of volume.

If people are used to looking at a slider when adjusting volume then they will be looking for a slider here too. We can't ignore that the video window conditions users to do that, and that deviating from it is most likely an unnecessary inconvenience.

The really awkward part is having volume control in a popover, making scrolling a much more inviting method for adjusting it. Not that it isn't more convenient even if the slider were visible, but I wouldn't be surprised if people acutally *discover* the slider by using scrolling.

**Comment by anohren** [comment]
Ok, I've tried this PR now and it seems to work beautifully. 

Except the first time I scrolled the popover spawned outside the window, but that might just be a Cocoa quirk.

**Comment by lhc70000** [comment]
Merged via 17fe851.

**Comment by lhc70000** [comment]
BTW, It looks way better than I thought!

**Pull request closed without merging**
