### PR TITLE
Correct label/tooltip for Safari toolbar button

### PR DESCRIPTION
**Pull request by anohren**

### CODE REVIEW

**Comment by alejx** [comment]
Do you know what does it effect?

**Comment by anohren** [comment]
@alejx Yes, the tooltip. And the label, when customizing the toolbar.

**Comment by alejx** [comment]
Then thanks for you fix!

**Comment by saagarjha** [comment]
This seems reasonable then. Let me merge it.

**Comment by saagarjha** [comment]
…I guess I'm too slow?

**Pull request merged**
