### PR TITLE
Begone, pods!

### PR DESCRIPTION
**Pull request by WowbaggersLiquidLunch**
- [x] This change has been discussed with the author.
- [x] It implements / fixes issue #2867.

---

### Changes

The CocoaPods environment is removed.

`iina.xcworkspace` is removed.

The same versions of PromiseKit and GzipSwift already support SwiftPM, and are added back through SwiftPM.

IINA maintains its own version of GRMustache.swift. Although IINA's GRMustache.swift already supports SwiftPM, it is 8 commits behind the upstream, so I added the upstream version through SwiftPM.

IINA maintains its own version of Just. IINA's Just has some compiler flags and other settings whose presence I'm not able to verify in the upstream. I don't know how much they matter, either. So, I added IINA's Just's `swift-5` branch through SwiftPM.

~~Sparkle does not yet support SwiftPM. There has been discussions of it, and [Swift Evolution proposal 271][SE-0271] paved the way for it. However, until it has full SwiftPM support, it has to be added and linked manually, which is what I did.~~ **Edit 2021-02-05**: Sparkle now works with SwiftPM, and is added to the project via SwiftPM in this PR.

### Testing

Surprisingly, there are not test cases, so I just built it and played a video. As far as I can tell, it worked. There is a buildtime warning, however. Please see [Caveats](#caveats) for details.

### Caveats

~~There is a buildtime warning for linking Sparkle:~~

> ~~`ld: warning: directory not found for option '-F/Users/wowbagger/parent/directories/ommited/iina/Sparkle-1.23.0'`~~

~~According to [Sparkle's documentation][sparkle doc], I need to set runpath search paths to `@loader_path/../Frameworks` in build settings. However, it's already set to `@executable_path/../Frameworks`. I left it unchanged, because I'm not sure how it might affect existing dependencies/frameworks if it's changed.~~

[SE-0271]: https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md
[sparkle doc]: https://sparkle-project.org/documentation/

### CODE REVIEW

**Comment by WowbaggersLiquidLunch** [comment]
^ I think the Travis CI build failure is because it's configured to build with CocoaPods.

**Comment by WowbaggersLiquidLunch** [comment]
Just tried `@loader_path/../Frameworks`. The warning persists.

**Comment by WowbaggersLiquidLunch** [comment]
Forgot to push 1 commit yesterday.

Also, just checked the update feature. Update still works despite the buildtime warning.

**Comment by saagarjha** [comment]
A couple of questions before I look at this in more detail:

> The CocoaPods environment is removed.

How did you do this? `pod deintegrate`?

> IINA maintains its own version of GRMustache.swift. Although IINA's GRMustache.swift already supports SwiftPM, it is 8 commits behind the upstream, so I added the upstream version through SwiftPM.

I think we want to keep the vendored version for now, as the upstream doesn't seem to be actively maintained. I'll pull from upstream and push it to our fork.

> IINA maintains its own version of Just. IINA's Just has some compiler flags and other settings whose presence I'm not able to verify in the upstream. I don't know how much they matter, either. So, I added IINA's Just's swift-5 branch through SwiftPM.

I'll take a look.

> Surprisingly, there are not test cases, so I just built it and played a video. As far as I can tell, it worked.

Yeah, we need testing ;)

> There is a buildtime warning for linking Sparkle

I'll take a look and see what we need. The new frameworks might need something different. Quick question about Sparkle: which branch did you take this from?

**Comment by WowbaggersLiquidLunch** [comment]
> > The CocoaPods environment is removed.
> 
> How did you do this? `pod deintegrate`?

I did use `pod deintegrate`. I tried to find more details from my bash history, but I couldn't find any. I might have used `pod cache clean --all` too, but I can'r remember. I just tried it on my local branch, and there is no effect Git-wise, so it shouldn't matter. Either `pod deintegrate` automatically removed `Podfile`, or I removed it manually. I forgot to remove `Podfile.lock` previously, but it's removed now. I removed `iina.xcworkspace` manually. 

---

> > IINA maintains its own version of GRMustache.swift. Although IINA's GRMustache.swift already supports SwiftPM, it is 8 commits behind the upstream, so I added the upstream version through SwiftPM.
> 
> I think we want to keep the vendored version for now, as the upstream doesn't seem to be actively maintained. I'll pull from upstream and push it to our fork.

I tried switching the SwiftPM from tracking the 4.* release of upstream version to the master branch of IINA's version, but the Swift versions are incompatible:

> package at 'https://github.com/iina/GRMustache.swift' @ a46e65d00b4753449b90465be813bbdb1a9ffc9d is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version:5.2' to specify the current tools version

Pulling from upstream should fix it. 

---

> Quick question about Sparkle: which branch did you take this from?

I didn't take it from any branch. I just used the [latest release 1.23.0](https://github.com/sparkle-project/Sparkle/releases/tag/1.23.0). It has to be updated manually for now, until Sparkle has full SwiftPM support.

---

Today I found out that `iina.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/` wasn't tracked in the repository, so I added it in.

**Comment by WowbaggersLiquidLunch** [comment]
> There is a buildtime warning for linking Sparkle

I think the warning is partially because `Framework` in the project is a group without a folder.

**Comment by WowbaggersLiquidLunch** [comment]
Sparkle now technically has [full SPM support](https://github.com/sparkle-project/Sparkle/pull/1634). I reverted the 2 commits where I added Sparkle as manually added dependencies. I converted this pull request to a draft for now, waiting for Sparkle to release a new zip archive, for it to be readily added to iina as an SPM-managed dependency. Once the zip archive comes, I'll add it to iina's project settings.

Additionally, I removed and untracked `Package.resolved` and `IDEWorkspaceChecks.plist`, because they shouldn't have been tracked/added.

**Comment by saagarjha** [comment]
Thanks for keeping this up-to-date, even though we haven’t shown it much love. Getting this reviewed and merged is on my list of things I would like to do, but sadly I haven’t gotten the time to get around to it yet…I’ll try my best to look at this at some point, perhaps when I take a break from looking at our Apple silicon story.

**Comment by thebluepotato** [comment]
Sparkle yesterday released their latest update including support for SPM that I drafted. Hope this can help IINA advance to a Pod-free future

**Comment by WowbaggersLiquidLunch** [comment]
Thank you for your work on Sparkle to make it possible, Jonas!

I created a new branch [`begone-pods2`](https://github.com/WowbaggersLiquidLunch/iina/tree/begone-pods2) yesterday to retry replacing pods with SwiftPM, because there were too many conflicts when rebasing this one. I'll open a new pull request that supersedes this one when it's ready. Meanwhile, there is still a problem preventing Sparkle from being added as a SwiftPM-managed dependency. I opened an issue sparkle-project/Sparkle#1674 for it.

**Comment by WowbaggersLiquidLunch** [comment]
Update: Sparkle just released [1.25.0rc1](https://github.com/sparkle-project/Sparkle/releases/tag/1.25.0rc1), but SwiftPM cannot resolve the version tag, so we'll have to wait for at least 1 more release before this PR is ready.

**Comment by WowbaggersLiquidLunch** [comment]
Now that Sparkles works via SwiftPM, I've redone this PR by doing exactly the same thing as I originally did in this PR, plus adding Sparkles via SwiftPM to the project.

Sparkles is set to track the latest tagged version < 2.0.0.

@saagarjha Could you re-review this PR?

**Comment by WowbaggersLiquidLunch** [comment]
I just updated the CI script, so that it could work with the new "install dependencies" step and SwiftPM binary dependencies. But it seems that I've broken it.

**Review by alejx — APPROVED** [review]

**Pull request merged**
